M48
; DRILL file {KiCad 7.0.7} date Sun Mar 31 00:03:11 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-31T00:03:11-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X8.1988Y-4.1929
X8.7402Y-3.0217
X8.7402Y-3.8287
T0
M30
